M48
; DRILL file {KiCad 7.0.7+dfsg-1} date Thu 04 Apr 2024 18:04:15 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-04T18:04:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X110.0Y-87.4
X110.0Y-148.0
X143.0Y-87.4
X143.0Y-148.0
T0
M30
